baseURL: http://bios-net.github.io
languageCode: de-DE
title: BIOS Netzwerk
paginate: 5
theme: "PaperModX"

defaultContentLanguage: de
languages:
    de:
      contentDir: "content/deutsch"
      title: BIOS Netzwerk

    en:
      contentDir: "content/english"
      title: Research Network BIOS

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: BIOS Netzwerk
  description: "BIOS Netzwerk. Forschungsnetzwer Bios, Technologien, Gesellschaft"
  keywords: ["Netzwerk", "Biopolitik", "Forschung"]
  author: ["Henning", "Iris"]
  # author: ["Me", "You"] # multiple authors
  images: ["/bilder"]
  DateFormat: "02. January 2006"
  defaultTheme: light
  disableThemeToggle: false
  ShowBreadCrumbs: true

  editPost:
    URL: "mailto://mail@example.com?subject=Suggesting changes for "
    Text: "Ergänzung vorschlagen" # edit text
    appendFilePath: true # to append file path to Edit link

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "BIOS"
    icon: /apple-touch-icon.png
    iconHeight: 35

  homeInfoParams:
      Title: "Forschungsnetzwerk // BIOS, Technologien, Gesundheit"
      Content: |
        ## Wer?
        BIOS ist eine Zusammenschluss von Forschenden aus unterschiedlichen Zusammenhängen, die sich mit der Verschränkung von Technologien, Biopolitiken, Ökonomie, Reproduktion und Gesundheit auseinandersetzen. 

        ## Was?
        Im Kern stehen die jährlichen Treffen, die den Austausch über empirische Arbeiten mit der Vertiefung theoretischer Auseinandersetzungen mit dem Leben verbinden.

        Ausführlicher auch hier: **[About](https://bios-net.github.io/about/)**.

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/hfueller/hfueller.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: About
      name: About
      url: /categories/about
      weight: 10
    - identifier: Treffen
      name: Treffen
      url: /categories/treffen
      weight: 20
    - identifier: Arbeiten
      name: Arbeiten
      url: /categories/work
      weight: 30
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 40


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
